In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [2]:
#scalar
scalar = torch.tensor(5)
scalar

tensor(5)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

5

In [5]:
#vector
vector=torch.tensor([5,5])
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
matrix=torch.tensor([[7,9,4],[1,2,2]])
matrix

tensor([[7, 9, 4],
        [1, 2, 2]])

In [8]:
matrix.ndim

2

In [9]:
matrix[1]

tensor([1, 2, 2])

In [10]:
matrix.shape

torch.Size([2, 3])

In [11]:
#tensor
TENSOR=torch.tensor([[[1,2],[3,4],[5,6]]])
TENSOR

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 2])

In [14]:
#ex1
ex1=torch.tensor([[4,3,2,1,1,1,1],[4,3,2,1,1,1,1],[4,3,2,1,1,1,1],[4,3,2,1,1,1,1],[4,3,2,1,1,1,1],[4,3,2,1,1,1,1],[4,3,2,1,1,1,1]])
ex1.shape

torch.Size([7, 7])

In [15]:
import torch

random_tensor = torch.rand(7, 7)  # Remove parentheses

print(random_tensor)

tensor([[0.8780, 0.3074, 0.7220, 0.0487, 0.1288, 0.4787, 0.1698],
        [0.4699, 0.6371, 0.1467, 0.3329, 0.2566, 0.7093, 0.0911],
        [0.4632, 0.3295, 0.4825, 0.5262, 0.8327, 0.7246, 0.9813],
        [0.2366, 0.7851, 0.9384, 0.2487, 0.1381, 0.4912, 0.1444],
        [0.6373, 0.5491, 0.2711, 0.0823, 0.7945, 0.1984, 0.6918],
        [0.9761, 0.8159, 0.6170, 0.1943, 0.0449, 0.5564, 0.2659],
        [0.9532, 0.5214, 0.7545, 0.5069, 0.9560, 0.1675, 0.3734]])


In [16]:
random_image_tensor_cwh =torch.rand(size=(3,224,224))#image tensor with 3 color channels(rgb) width height

random_image_tensor_cwh.shape,random_image_tensor_cwh.ndim

(torch.Size([3, 224, 224]), 3)

In [17]:
#zero and one tensor
zero=torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
one=torch.ones(4,4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
#range of tensors and tensors like
like=torch.arange(start=1,end=1200,step=23)#goes from 1 to 11
like

tensor([   1,   24,   47,   70,   93,  116,  139,  162,  185,  208,  231,  254,
         277,  300,  323,  346,  369,  392,  415,  438,  461,  484,  507,  530,
         553,  576,  599,  622,  645,  668,  691,  714,  737,  760,  783,  806,
         829,  852,  875,  898,  921,  944,  967,  990, 1013, 1036, 1059, 1082,
        1105, 1128, 1151, 1174, 1197])

In [20]:
torch.zeros_like(like)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0])

In [21]:
float16_tensor=torch.tensor([300,4,5],dtype=torch.float16,device=None)#device can be gpu or cuda cpu==none
float16_tensor.dtype

torch.float16

In [22]:
#convert tensor
float32_tensor=float16_tensor.type(torch.float32)
float32_tensor.dtype

torch.float32

In [23]:
float32_tensor*float16_tensor

tensor([9.0000e+04, 1.6000e+01, 2.5000e+01])

In [24]:
int32t=torch.tensor([3,4,5],dtype=torch.int32)
int32t

tensor([3, 4, 5], dtype=torch.int32)

In [25]:
#datatype shape and device of tensor
test_tensor=torch.rand(3,9)
print(f" Datatype: {test_tensor.dtype} \n Shape: {test_tensor.shape} \n Device: {test_tensor.device}")

 Datatype: torch.float32 
 Shape: torch.Size([3, 9]) 
 Device: cpu


In [26]:
#mainpulating tensors
tensor = torch.tensor([1,2,3])
print(tensor+10)
print(tensor*10)
print(tensor-10)
print(torch.mul(tensor,10))

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([10, 20, 30])


In [27]:
#matrix multiplication (dot product)
%%time
torch.matmul(tensor,tensor)

CPU times: user 370 µs, sys: 66 µs, total: 436 µs
Wall time: 2.42 ms


tensor(14)

In [28]:
r1=torch.rand(3,4)
r2=torch.rand(3,4)
torch.matmul(r1,r2.T)

tensor([[1.3635, 2.1158, 1.5769],
        [0.6271, 1.2109, 0.7483],
        [0.8711, 1.1632, 0.9055]])

In [29]:
#finding min max mean and sum (matrix aggregation)
test = torch.rand(3,3)
print(test)
print(torch.min(test))
print(torch.max(test))
print(torch.mean(test))
print(torch.sum(test))
#datatype needs to be a float or complex for the operation to work
print(torch.mean(torch.arange(start=1,end=1200,step=23).type(torch.float16)))
print(torch.argmin(test))
print(torch.argmax(test))

tensor([[0.1812, 0.6553, 0.9313],
        [0.9340, 0.8814, 0.8818],
        [0.6966, 0.7464, 0.3272]])
tensor(0.1812)
tensor(0.9340)
tensor(0.6928)
tensor(6.2353)
tensor(599., dtype=torch.float16)
tensor(0)
tensor(3)


In [37]:
xtensor=torch.arange(1,11,dtype=torch.float32)
xtensor.shape

torch.Size([10])

In [38]:
#reshaping
xtensor_rehaped=xtensor.reshape(1,10)
print(xtensor_rehaped)
xtensor_rehaped=xtensor.reshape(10,1)
print(xtensor_rehaped)
xtensor_rehaped=xtensor.reshape(5,2)
print(xtensor_rehaped)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


In [41]:
#views
ztensor=xtensor.view(5,2)
print(ztensor)
print(xtensor)
#changing value in views changes the original
ztensor[0,0]=23
ztensor,xtensor

tensor([[23.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
tensor([23.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


(tensor([[23.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 tensor([23.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [44]:
#stack
xstack=torch.stack([xtensor,xtensor,xtensor,xtensor],dim=1)
xstack

tensor([[23., 23., 23., 23.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [46]:
#squeeze removes the 1 in 1 10
xtensor_rehaped=xtensor.reshape(1,10)
print(xtensor_rehaped.shape)
print(xtensor_rehaped.squeeze())
print(xtensor_rehaped.squeeze().shape)

torch.Size([1, 10])
tensor([23.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
torch.Size([10])


In [51]:
#unsqueeze adds the 1 in 1 10
squeezed=xtensor_rehaped.squeeze()
print(squeezed.shape)
print(squeezed)
print(squeezed.unsqueeze(dim=1).shape)
print(squeezed.unsqueeze(dim=1))


torch.Size([10])
tensor([23.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
torch.Size([10, 1])
tensor([[23.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])


In [53]:
#permute rearranges the tensor and returns a view
original=torch.rand(size=(224,224,3))
permuted=original.permute(2,0,1) #3 goes to the beggining first 224 becomes second second 224 becomes third
print(original.shape)
print(permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


In [54]:
#indexing
indexing=torch.arange(1,10).reshape(1,3,3)
indexing,indexing.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [59]:
indexing[0,1,2]

tensor(6)

In [67]:
indexing[:,:,1]#gets the columns

tensor([[2, 5, 8]])

In [ ]:
#you can use pytorch interchangibly with numpy using torch.from_numpy() and export to numpy using torch.numpy()

In [75]:
#reproducibility
custom_seed=12
torch.manual_seed(custom_seed)
randa=torch.rand(3,3)
torch.manual_seed(custom_seed)
randb=torch.rand(3,3)
print(randa)
print(randb)

tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272],
        [0.6373, 0.2421, 0.7312]])
tensor([[0.7224, 0.1992, 0.6948],
        [0.5830, 0.6318, 0.5559],
        [0.1262, 0.9790, 0.8443]])


In [1]:
#running in the gpu
!nvidia-smi

Sun Mar 10 12:01:30 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
#check for gpu
import torch
torch.cuda.is_available()

True

In [3]:
#setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
tensor=torch.tensor([1,2,3],device="cuda")#if you dont specify it runs on the cpu
tensor.device

device(type='cuda', index=0)

In [9]:
tensor=torch.tensor([23,23,26])
print(tensor.device)
gputensor=tensor.to(device)
print(gputensor.device)
back_to_cpu=gputensor.cpu()
print(back_to_cpu.device)

cpu
cuda:0
cpu
